ALLOWED_YEARS = ["Freshman", "Sophomore", "Junior", "Senior", "Graduate"]

ALLOWED_COMFORT_LEVELS = [
    "open to messages",
    "prefers intro message",
]

ALLOWED_TAGS = [
    "academic stress",
    "course registration",
    "research decisions",
    "internship search",
    "changing majors",
    "time management",
    "burnout",
    "making friends",
    "dating",
    "social life",
    "social anxiety",
    "joining clubs",
    "anxiety",
    "campus navigation",
    "housing",
    "freshman adjustment",
    "transfer student",
    "international student adjustment",
]

ALLOWED_HELP_TOPICS = [
    "academic advising",
    "academic planning",
    "academic stress",
    "burnout recovery",
    "campus navigation",
    "campus relationships",
    "campus resources",
    "campus social life",
    "changing majors",
    "club involvement",
    "communication",
    "course registration",
    "cultural adaptation",
    "dating",
    "dorm social dynamics",
    "freshman adjustment",
    "grad school vs industry",
    "housing",
    "housing conflicts",
    "international student adjustment",
    "internship search",
    "interview prep",
    "joining clubs",
    "making friends",
    "managing expectations",
    "networking",
    "research decisions",
    "roommate communication",
    "social anxiety",
    "social life",
    "study skills",
    "time management",
    "transfer adjustment",
]
